import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { Notification } from 'electron'
import type { PostureAlert, Stage } from '../shared/posture'
import { composeToast, CopyPicker } from './notification-copy'
import { getPauseState } from './pause'
import { resourcesDir } from './resources'
import { getSettings } from './settings-store'
import { showMainWindow } from './window'

const picker = new CopyPicker()

/**
 * Toast logo: the spine glyph bent the way this issue bends it, in the
 * stage's color (resources/toast, generated by scripts/gen-icons.mjs).
 */
function toastIcon(name: string): string | undefined {
  const file = join(resourcesDir(), 'toast', `${name}.png`)
  return existsSync(file) ? file : undefined
}

/**
 * The renderer's episode state machines decide WHEN an alert is warranted
 * (dwell, hysteresis, cooldown, escalation) — this module only decides
 * WHETHER the user wants to hear about it, and renders the toast.
 */
export function fireAlert(alert: PostureAlert): void {
  const s = getSettings()
  if (getPauseState().paused) return // a last frame can race the pause switch
  if (!s.notifications.enabled) return
  if (alert.kind === 'recovery') return // v1: tracked silently
  const issue = s.issues[alert.issue]
  if (!issue?.enabled) return
  if (alert.stage < 1 || alert.stage > 3) return
  if (!issue.notifyStages[(alert.stage - 1) as 0 | 1 | 2]) return
  if (alert.kind === 'escalation' && !s.notifications.escalation) return

  const { title, body } = composeToast(alert, picker)
  showToast(title, body, !s.notifications.sound, toastIcon(`${alert.issue}-${alert.stage}`))
}

export function testNotification(): void {
  showToast(
    'SitSense test notification',
    'Nudges will look like this. If you never see them, check Windows notification settings for SitSense.',
    !getSettings().notifications.sound,
    toastIcon('good')
  )
}

export function trayHint(): void {
  showToast('SitSense is still watching', 'Monitoring continues from the tray. Quit via the tray menu.', true)
}

function showToast(title: string, body: string, silent: boolean, icon?: string): void {
  if (!Notification.isSupported()) return
  const n = new Notification({ title, body, silent, ...(icon ? { icon } : {}) })
  n.on('click', () => showMainWindow())
  n.show()
}

export function stageLabel(stage: Stage): string {
  return (['fine', 'slight', 'clear', 'severe'] as const)[stage]
}
